INSERT INTO Category (id, name, thumbnail, categoryurl, createTimestamp) VALUES (1, '資訊', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createTimestamp) VALUES (2, '正妹', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/J0lXGUg.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createTimestamp) VALUES (3, '生活', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/lSoGKrH.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (4, '其他議題', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (5, '研究', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (6, '資源', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (7, 'iphoneapp', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (8, '新聞', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (9, 'it-news', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (10, '#NewsSquares.XL', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (11, '手機', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (12, 'English', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (13, '財經', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (14, 'PTT', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (15, 'IPA', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (16, '基金', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());
INSERT INTO Category (id, name, thumbnail, categoryurl, createtimestamp) VALUES (17, '商業', 'https://i.imgur.com/dsECxwV.jpg', 'https://i.imgur.com/dsECxwV.jpg', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, thumbnail, createTimestamp) VALUES (1, 'Engadget', 'http://feeds.feedburner.com/engadget/cstb', '', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, thumbnail, createTimestamp) VALUES (1, 'bnext', 'http://www.bnext.com.tw/feed/rss/topicslinks', '', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, thumbnail, createTimestamp) VALUES (1, 'iphone TW', 'http://feeds.feedburner.com/Iphonetw', '', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, thumbnail, createTimestamp) VALUES (2, '美女寫真館', 'http://a305020.pixnet.net/blog/feed/rss', '', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, thumbnail, createTimestamp) VALUES (2, '正妹日報', 'http://blog.xuite.net/louiewong/blog/rss.xml', '', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, thumbnail, createTimestamp) VALUES (2, '正妹星球', 'http://ookkk.blogspot.com/feeds/posts/default', '', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, thumbnail, createTimestamp) VALUES (3, '動腦-即時新聞', 'http://www.brain.com.tw/Resource/Rss_News.aspx', '', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, thumbnail, createTimestamp) VALUES (3, '閱讀迷走', 'http://www.readgoing.com/?feed=rss2', '', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, thumbnail, createTimestamp) VALUES (3, '奇摩電影', 'http://tw.movie.yahoo.com/rss/headline', '', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (5,'RCSB Protein Data Bank','http://www.rcsb.org/pdb/rss/LastLoad','http://www.rcsb.org/pdb/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (5,'Proteins: Structure, Function, and Bioinformatics','http://www3.interscience.wiley.com/rss/journal/36176','http://onlinelibrary.wiley.com/resolve/doi?DOI=10.1002%2F%28ISSN%291097-0134', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (5,'BMC Bioinformatics - Latest Articles','http://www.biomedcentral.com/bmcbioinformatics/rss','http://bmcbioinformatics.biomedcentral.com', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (4,'美容討論區最新文章|::.UrCosme.::化妝品使用心得入口網站','http://www.urcosme.com.tw/rss/bbs_topnew.xml','http://www.urcosme.com/boards/topnew.htm', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (4,'中時理財網-房地產研究報告','http://rss.chinatimes.com/rss/M_estate-u.rss','http://money.chinatimes.com/invest/estate/main.htm?source=rss', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (4,'Yahoo!奇摩新聞-教育','http://tw.news.yahoo.com/rss/edu','https://tw.news.yahoo.com/education/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (4,'Auto Online汽車線上資訊網  最新報導','http://www.auto-online.com.tw/rss_reader.php','http://www.auto-online.com.tw', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (4,'壽司貓 慵懶地帶','http://www.sushicat.net/bbs/rss.php','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (4,'Yahoo!奇摩電影-電影頭條','http://tw.movie.yahoo.com/rss/headline','https://tw.movies.yahoo.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (4,'AutoNet 汽車日報 完整版','http://www.autonet.com.tw/rss/autonet.xml','http://www.autonet.com.tw/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (4,'影類-影展','http://www.google.com/calendar/feeds/n3h512lsib0bniroejl90j36t0@group.calendar.google.com/public/basic','http://www.google.com/calendar/embed?src=n3h512lsib0bniroejl90j36t0%40group.calendar.google.com', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'海芋小站','http://feedproxy.google.com/inotetw','http://www.inote.tw', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Gear Diary','http://feeds.feedburner.com/GearDiary','https://geardiary.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Inside','http://www.inside.com.tw/feed','https://www.inside.com.tw', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Apple iPhone iPad 最棒的華語影音教學網站','http://feeds.feedburner.com/iphone4TW','http://iphone4.tw/forums/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'龍騰下載網','http://download.longtermly.com/feed/','http://download.longtermly.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'ifanr 爱范儿 ♂专注于拇指设备的小众讨论','http://www.ifanr.com/feed','http://www.ifanr.com?utm_source=rss&utm_medium=rss&utm_campaign=', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'黃子嘉 - 線代離散研究室','http://zjhwang.blogspot.com/feeds/posts/default','http://zjhwang.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'World News from Times Online','http://feeds.timesonline.co.uk/c/32313/f/440158/index.rss','http://www.timesonline.co.uk', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'交大資工公告 - 系內公告','http://www.cs.nctu.edu.tw/cht/announcements/post/rss/?class=1','http://www.cs.nctu.edu.tw/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Fun iPhone 愛瘋玩家:: 痞客邦 PIXNET ::','http://funiphone.pixnet.net/blog/feed/rss','http://funiphone.pixnet.net/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'免費資源網路社群','http://feeds.freegroup.org/freegroup?format=xml','https://free.com.tw', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'iPhoneTW台灣iPhone俱樂部','http://feeds.feedburner.com/Iphonetw','http://www.iphonetw.net', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'熱門轉噗排行榜 PlurkTop','http://plurktop.mmdays.com/feed','http://plurktop.mmdays.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'數位時代 Beta3.0 | Topics ＆ Links','http://www.bnext.com.tw/feed/rss/topicslinks','http://www.bnext.com.tw/Feed/rss/topicslinks', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'熱門焦點部落格:: 痞客邦 PIXNET ::','http://todo.pixnet.net/blog/feed/rss','http://todo.pixnet.net/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Readgoing 閱讀迷走','http://www.readgoing.com/?feed=rss2','http://readgoing.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'吉米丘上的部落格','http://feeds.feedburner.com/acykjcms','http://blog.jcms.com.tw', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'㊣軟體玩家','http://feeds.feedburner.com/quicktop','https://pcrookie.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'TechCrunch','http://www.techcrunch.com/feed/','https://techcrunch.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'電腦玩物','http://feeds.feedburner.com/playpc','http://www.playpcesor.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'RainDog:: 痞客邦 PIXNET ::','http://raindog.pixnet.net/blog/feed/rss','http://raindog.pixnet.net/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'c jay''s tech blog','http://www.wretch.cc/blog/jay506&rss20=1','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'朱學恒的阿宅萬事通事務所','http://blogs.myoops.org/lucifer.php?tempskin=_rss2','http://blogs.myoops.org/lucifer.php', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Engadget','http://www.engadget.com/rss.xml','http://www.engadget.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Crave 科技瘋','http://feeds.feedburner.com/cnettw/crave','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'The Firmware Umbrella - TinyUmbrella','http://thefirmwareumbrella.blogspot.com/feeds/posts/default','http://thefirmwareumbrella.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'iPhone4 專屬中文社群網站','http://feeds.feedburner.com/iphone4TW?format=xml','http://iphone4.tw/forums/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'內容推進實驗室','http://feeds.feedburner.com/contnt','http://www.contnt.net/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Red Sweater Blog','http://www.red-sweater.com/blog/feed','https://red-sweater.com/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'社交網站收集與研究 (MMDays)','http://feeds2.feedburner.com/mmdays-sn','http://socialnetwork.mmdays.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'凱文的網路創業觀察:: 痞客邦 PIXNET ::','http://webman.pixnet.net/blog/feed/rss','http://webman.pixnet.net/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Loda''s blog','http://loda.hala01.com/feed/','http://loda.hala01.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'ApplePlan','http://appleplan.com.tw/blog/feed','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'MacUknow','http://feeds.feedburner.com/macuknow?format=xml','http://www.macuknow.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'PCuSER 電腦人:: 痞客邦 PIXNET ::','http://blog.pixnet.net/rss/rss20/pcuser','http://pcuser.pixnet.net/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'InspireGate | InspireGate 派克空間','http://inspire.twgg.org/?format=feed&type=rss','http://inspiregate.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'白银黄金--当今最值得拥有的财富 - 金皇华府 - 和讯博客','http://byhj.blog.hexun.com/rss2.aspx','http://byhj.blog.hexun.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'威峰網-iphone','http://bbs.weiphone.com/rss.php?fid=36','http://bbs.weiphone.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'TechNews 科技新報','http://technews.tw/feed/','http://technews.tw', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'重灌狂人','http://feeds.feedburner.com/briian?format=xml','https://briian.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'綠色工廠 Easylife Blog','http://portable.easylife.idv.tw/rss','http://easylife.tw', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Macworld','http://rss.macworld.com/macworld/feeds/main','http://www.macworld.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Tech and Web from Times Online','http://feeds.timesonline.co.uk/c/32313/f/463699/index.rss','http://www.timesonline.co.uk', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'香腸炒魷魚','http://feeds.feedburner.com/s9011514','https://sofree.cc', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'數位內容觀察站','http://digicontent.blogspot.com/feeds/posts/default','http://digicontent.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'♣梅問題‧教學網【Minwt】♣','http://www.minwt.com/?feed=rss2','https://www.minwt.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Solidot','http://solidot.org.feedsportal.com/c/33236/f/556826/index.rss','http://www.solidot.org', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'就是教不落','http://feeds2.feedburner.com/steach','https://steachs.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'居家生活 8J Living - 室內設計 裝潢 家電 傢俱 創意設計 建築 生活用品','http://8jliving.com/rss.xml','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'大人物','http://daman.cool3c.com/daman/rss','http://www.damanwoo.com/daman/rss', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'0與1的邂逅','http://feeds.feedburner.com/joaoko','http://blog.joaoko.net', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'創新使用者互動介面研究 (UIUI)','http://feeds.feedburner.com/uiui','http://uiui.mmdays.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'演算法筆記 - 最新消息','http://djws.wordpress.com/feed/','https://djws.wordpress.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'OIKOS 生活網','http://feeds.feedburner.com/com/WvuX','http://www.oikos.com.tw/v4/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'iLounge | All Things iPod, iPhone, iTunes and beyond','http://feeds.feedburner.com/ilounge','http://www.iLounge.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'威鋒網-MAC','http://bbs.weiphone.com/rss.php?fid=68','http://bbs.weiphone.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Ward No. 6','http://feeds.feedburner.com/WardNumber6','http://blog.richi.cc/tai', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'老地方冰果室','http://www.frostyplace.com/rss.php','http://www.frostyplace.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Boy Genius Report','http://feeds.feedburner.com/TheBoyGeniusReport?format=xml','http://bgr.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Mr./Ms. Days (MMDays) - 網路, 資訊, 觀察, 生活','http://feeds2.feedburner.com/mmdays','http://mmdays.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'時尚新聞','http://reynard-news.blogspot.com/feeds/posts/default?alt=rss','http://reynard-news.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'appleseed, 蘋果核','http://feeds.feedburner.com/Appleseed','http://blog.roodo.com/appleseed/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Mr. PM','http://feeds.feedburner.com/pmmustknow','http://mrpm.cc', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'NCTU Library 新書通報(CCL:)','http://webpac.lib.nctu.edu.tw:8080/nbr/reader/rbn_rss.jsp?C=CCL','http://webpac.lib.nctu.edu.tw/F?func=file&file_name=find-c-na&local_base=topnb', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Jamyy''s Weblog','http://cha.homeip.net/blog/index.xml','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Howettblog®','http://blog.howett.net/feed/','http://blog.howett.net', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'艾瑞克-極品獵豔:: 痞客邦 PIXNET ::','http://ericgj.pixnet.net/blog/feed/rss','http://ericgj.pixnet.net/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Jackbin 的懶人筆記','http://feeds.feedburner.com/jackbin','http://jackbin.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'iphone.org.hk','http://www.iphone.org.hk/cgi-bin/ch/rss.cgi','http://www.iphone.org.hk/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Engadget 中文版','http://chinese.engadget.com/rss.xml','http://chinese.engadget.com/rss.xml', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'Slashdot','http://rss.slashdot.org/Slashdot/slashdot','https://slashdot.org/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'iCodeBlog','http://feeds.feedburner.com/icodeblog?format=xml','http://www.icodeblog.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (6,'RakunaMac:: 痞客邦 PIXNET ::','http://rakunamac.pixnet.net/blog/feed/rss','http://rakunamac.pixnet.net/blog', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (7,'正妹寫真館:: 痞客邦 PIXNET ::','http://v520.pixnet.net/blog/feed/rss','http://v520.pixnet.net/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (7,'iPhoneBlogspot','http://iphoneipodtouch.blogspot.com/feeds/posts/default','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (7,'威锋网(jp)','http://mrss.dokoda.jp/a/http/bbs.weiphone.com/rss.php?fid=36','http://bbs.weiphone.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (7,'威锋网 [feedex.net]','http://feedex.net/feed/bbs.weiphone.com/rss.php?fid=36','http://bbs.weiphone.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (7,'博酷网 [feedex]','http://feedex.net/feed/bbs.pockoo.com/rss.php?fid=45&auth=0','http://bbs.pockoo.com/forumdisplay.php?fid=45', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (8,'焦點新聞 - Google 新聞','http://news.google.com.tw/news?pz=1&cf=all&ned=tw&hl=zh-TW&topic=h&num=3&output=rss','http://news.google.com.tw/news?hl=zh-TW&pz=1&ned=tw&num=3&topic=h', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (8,'【新聞稿中心】','http://feeds.feedburner.com/sinwen?format=xml','https://123.briian.com/forum.php?mod=forumdisplay&fid=32', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (8,'動腦-即時新聞','http://www.brain.com.tw/Resource/Rss_News.aspx','http://www.brain.com.tw', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (9,'爱苹果','http://iapple.pcpop.com/feed','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (9,'CnFan.Org','http://feeds.feedburner.com/cnfan','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (9,'Chrome迷','http://feeds.feedburner.com/chromi','http://www.chromi.org', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (9,'cnBeta.COM','http://cnbeta.com/backend.php','http://www.cnbeta.com', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (10,'威峰網-iphone','http://bbs.weiphone.com/rss.php?fid=36','http://bbs.weiphone.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (10,'Apple iPhone iPad 最棒的華語影音教學網站 - 8,9,12,13,14,22,23,25,26,27,39,40,41,42,46,47,51,52,60,67,69,70,71,74,80,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,114,115,116,117,122,123','http://feeds.feedburner.com/iphone4TW','http://iphone4.tw/forums/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (10,'Yahoo!奇摩新聞-財經','http://tw.news.yahoo.com/rss/biz','https://tw.news.yahoo.com/finance/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (10,'Yahoo!奇摩新聞-教育','http://tw.news.yahoo.com/rss/edu','https://tw.news.yahoo.com/education/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (10,'iPhoneBlogspot','http://iphoneipodtouch.blogspot.com/feeds/posts/default','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (10,'每日英语 [expanded by feedex.net]','http://feedex.net/feed/english-feed.beanwoo.com/','http://blog.beanwoo.com/english', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (10,'巴哈姆特 GNN 新聞網','http://gnn.gamer.com.tw/rss.xml','https://gnn.gamer.com.tw/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (10,'威鋒網-MAC','http://bbs.weiphone.com/rss.php?fid=68','http://bbs.weiphone.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (10,'iPhone4 專屬中文社群網站','http://feeds.feedburner.com/iphone4TW?format=xml','http://iphone4.tw/forums/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (10,'cnBeta.COM','http://cnbeta.com/backend.php','http://www.cnbeta.com', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (11,'iphone Dev-Team Blog','http://blog.iphone-dev.org/rss','http://blog.iphone-dev.org/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (11,'手機GoGo - 專題新聞','http://www.gophone.com.tw/rss/news_rss.jsp','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (11,'iPhone Atlas','http://reviews.cnet.com/8300-19512_7-233.xml?tag=rtcol;about','https://www.cnet.com/#ftag=CAD4aa2096', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (11,'ePrice 比價王 綜合新聞','http://www.phonedaily.com/news/rss/news.xml','http://www.eprice.com.tw', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (12,'[廖柏森 英語與翻譯教學]部落格','http://mrss.dokoda.jp/a/http/blog.udn.com/rss.jsp?uid=trjason','http://blog.udn.com/trjason', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (12,'海词论坛 [expanded by feedex.net]','http://feedex.net/feed/bbs.dict.cn/rss.php?auth=0','http://bbs.dict.cn/index.php', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (12,'Writing ABC','http://writingabc.wordpress.com/feed/','https://writingabc.wordpress.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (12,'bbcukchina.com | 随身英语','http://www.bbc.co.uk/ukchina/simp/elt/take_away_english/index.xml','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (12,'每日英语 [expanded by feedex.net]','http://feedex.net/feed/english-feed.beanwoo.com/','http://blog.beanwoo.com/english', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (12,'BBC China | 英语教学 | Learning English [expanded by feedex.net]','http://feedex.net/feed/www.bbc.co.uk/china/learningenglish/index.xml','http://www.bbc.co.uk/go/wsy/pub/rss/1.0/-/china/learningenglish/index.shtml', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (12,'摩西英语','http://mrss.dokoda.jp/a/http/www.mosesenglish.com/rss/index.asp','http://www.mosesenglish.com/', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (13,'遊戲基地新聞-今日新聞','http://hardware.gamebase.com.tw/rss/hreport.rss','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (13,'巴哈姆特 GNN 新聞網','http://gnn.gamer.com.tw/rss.xml','https://gnn.gamer.com.tw/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (13,'HiNet遊戲網新聞週報','http://games.hinet.net/Home/home_news_rss.xml','', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'天天看女優','http://blog.xuite.net/netmeccc/mj3/rss.xml','http://blog.xuite.net/netmeccc/mj3', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'jays1943 分享正妹','http://blog.roodo.com/jays1943/rss.xml','http://blog.roodo.com/jays1943/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'Sexy asia girl','http://6ewong.blogspot.com/feeds/posts/default','http://6ewong.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'美女寫真館:: 痞客邦 PIXNET ::','http://a305020.pixnet.net/blog/feed/rss','http://a305020.pixnet.net/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'正妹日報．新站','http://blog.xuite.net/louiewong/blog/rss.xml','http://blog.xuite.net/louiewong/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'@AV漂流教室','http://formosa2008.blogspot.com/feeds/posts/default','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'美  顏  賞 ♥ 網路相簿美女 ♥ 690萬瀏覽人次達成','http://blog.xuite.net/ilovebmilk/ABCD/rss.xml','http://blog.xuite.net/ilovebmilk/ABCD', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'天天看正妹','http://blog.xuite.net/netmecc/mj/rss.xml','http://blog.xuite.net', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'天天看正妹','http://blog.xuite.net/netme/blog/rss.xml','http://blog.xuite.net/netme/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'正妹星球!! ♥  就是愛正妹','http://ookkk.blogspot.com/feeds/posts/default','http://ookkk.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'高挑美腿美女寫真集相簿收集處','http://highbeautygirl.blogspot.com/feeds/posts/default','http://highbeautygirl.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'美人邦部落格','http://blog.xuite.net/a305020/blog/rss.xml','http://blog.xuite.net/a305020/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (2,'美女尤物寫真館','http://jpbeautyhouse.blogspot.com/feeds/posts/default','http://jpbeautyhouse.blogspot.com/', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (14,'China Post Online - Taiwan Business,World Business','http://www.chinapost.com.tw/rss/business.xml','http://www.chinapost.com.tw/business', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (14,'Yahoo!奇摩新聞-財經','http://tw.news.yahoo.com/rss/biz','https://tw.news.yahoo.com/finance/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (14,'環球財經 市場要聞','http://www.chineseworldnet.com/scripts/services/rss2_news.asp','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (14,'上班族投資理財 - Invest In Taiwan Stock Market','http://www.pjhuang.net/rss.xml','http://blog.pjhuang.net/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (14,'永不老論壇','http://www.yongbulao.com/rss.php?fid=39','', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (15,'批踢踢實業坊 sex 板','http://rss.ptt.cc/sex.xml','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (15,'批踢踢實業坊 joke 板','http://rss.ptt.cc/joke.xml','http://rss.ptt.cc/joke.xml', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (15,'批踢踢實業坊 Gossiping 板','http://rss.ptt.cc/Gossiping.xml','', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (16,'iPhoneBlogspot','http://iphoneipodtouch.blogspot.com/feeds/posts/default','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (16,'威锋网(jp)','http://mrss.dokoda.jp/a/http/bbs.weiphone.com/rss.php?fid=36','http://bbs.weiphone.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (16,'iPhone vs IT','http://hkappleiphone.blogspot.com/feeds/posts/default','http://hkappleiphone.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (16,'威锋网 [feedex.net]','http://feedex.net/feed/bbs.weiphone.com/rss.php?fid=36','http://bbs.weiphone.com', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (16,'威锋网软件评测[feedex]','http://feedex.net/feed/lab.weiphone.com/rss.xml','http://lab.feng.com/index.shtml', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (16,'數碼iPhone軟件','http://forum.datcmobile.com/rss.php?fid=53&auth=0','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (16,'博酷网 [feedex]','http://feedex.net/feed/bbs.pockoo.com/rss.php?fid=45&auth=0','http://bbs.pockoo.com/forumdisplay.php?fid=45', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (17,'鉅亨最新公告','http://www.cnyes.com/promote/announce/GetRss.ashx','http://www.cnyes.com/PROMOTE/ANNOUNCE/scenario222.aspx', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (17,'Yahoo! Message Board - 基金','http://tw.money.mb.yahoo.com/fund/rss.html','', now());

INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'商業周刊 - 最新文章','http://www.businessweekly.com.tw/rss/bw_rss.xml','http://bw.businessweekly.com.tw/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'V怪客的電子商務怪談','http://talkec.blogspot.com/feeds/posts/default','http://talkec.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'Manager Today經理人｜最新數位焦點','http://www.managertoday.com.tw/rss.php?DisPlay=1','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'專案管理是一種生活思維:: 痞客邦 PIXNET ::','http://joechang.pixnet.net/blog/feed/rss','http://joechang.pixnet.net/blog', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'遠見雜誌網','http://www.gvm.com.tw/rss/rss.asp','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'Mr. Jamie 看網路與創投','http://feeds.feedburner.com/MrJamie','http://mrjamie.cc', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'Mr. 6 - 趨勢．創業．網路．生活','http://feeds.feedburner.com/mr6','http://mr6.cc', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'天下雜誌精選內容','http://www.cw.com.tw/RSS/cw_content.xml','http://www.cw.com.tw/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'维基百科：特色条目','http://zh.wikipedia.org/w/index.php?title=Template:Feature/rss&action=raw&ctype=application/rss+xml','http://zh.wikipedia.org/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'TiPb - The #1 iPhone, iPad, and iPod touch blog','http://feeds.feedburner.com/theiphoneblog','http://www.imore.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'CopZ 搖滾客 | 搖滾 x 設計 x 愛與和平','http://www.copz.com.tw/feed/','', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'IT 台灣郎','http://taiwanwolf.blogspot.com/feeds/posts/default','http://taiwanwolf.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'老人與蘋果','http://differentapple.blogspot.com/feeds/posts/default','http://differentapple.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'Mulberry的時間事件簿','http://timeimprint.blogspot.com/feeds/posts/default?alt=rss','http://timeimprint.blogspot.com/', now());
INSERT INTO Rss (categoryId, rssName, rssUrl, rssHtml, createTimestamp) VALUES (18,'Rocky Sand Studio News','http://rockysandstudio.com/tag/news/feed','http://www.rockysandstudio.com', now());